# Generated by Django 4.0.3 on 2022-03-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_alter_photo_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='arts.art'),
        ),
    ]
