# Generated by Django 4.0.3 on 2022-03-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_art_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='like_users',
        ),
    ]
