# Generated by Django 4.0.3 on 2022-03-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_email_confirmed_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('Gmail', 'Gmail'), ('kakao', 'Kakao')], default='Gmail', max_length=50),
        ),
    ]
