# Generated by Django 4.0.3 on 2022-03-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_like',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
