# Generated by Django 4.0.3 on 2022-03-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like_users',
        ),
    ]
