# Generated by Django 4.0.3 on 2022-03-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_like',
        ),
    ]
