# Generated by Django 4.0.3 on 2022-03-23 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0004_art_like_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0005_remove_review_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='arts.art'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
